name: 배포 병합 요청 생성

on: 
  push:
    branches:
      - main

jobs:
  create_release_pr:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v4

      - run: echo {{ github.pull_request.number }}