name: Create release PR

on:
  push:
    branches:
      - develop

permissions:
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check release PR is exist
        id: check
        run: |
          NUMBER=$(gh api /repos/${{ github.repository }}/pulls \
            -f head=akfakf0509:develop \
            -f base=main \
            -f state=open \
            -X GET \
            --jq .[0].number)
          echo "number=$NUMBER" >> "$GITHUB_OUTPUT"
      - name: Create Release PR if not exist
        if: ${{ !steps.check.outputs.number }}
        run: |
          NUMBER=$(gh api /repos/${{ github.repository }}/pulls \
            -f title="release: New features and fixes" \
            -f head=develop \
            -f base=main \
            -f draft=true \
            -X POST)
