name: 배포 병합 요청 생성

on: 
  push:
    branches:
      - develop

permissions:
  pull-requests: write

jobs:
  create_release_pr:
    runs-on: ubuntu-latest
    steps:
      - name: 깃허브 CLI
        
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api /repos/${{ github.repository }}/pulls -XGET -f 'base=main' -f 'head=akfakf0509:develop' --jq .[0].number
