name: 배포 병합 요청 생성

on: 
  push:
    branches:
      - develop

jobs:
  create_release_pr:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v4

      - name: 깃허브 CLI
        run: |
          gh api /repos/akfakf0509/release-pr-action/pulls -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28"
        env:
          GH_TOKEN: ${{ github.token }}
