name: 배포 병합 요청 생성

on: 
  push:
    branches:
      - develop

permissions:
  pull-requests: write

jobs:
  create_release_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Get Release PR
        id: get-pr
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PR_NUMBER=$(gh api /repos/${{ github.repository }}/pulls \
            -f head=akfakf0509:develop \
            -f base=main \
            -f state=open \
            --method GET \
            --jq .[0].number)
          echo "pr-number=$PR_NUMBER" >> "$GITHUB_OUTPUT"
      - name: Create Release PR if not exist
        id: create-pr
        if: ${{ !steps.get-pr.outputs.pr-number }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PR_NUMBER=$(gh api /repos/${{ github.repository }}/pulls \
          -f title="release: New features and fixes" \
          -f head=develop
          -f base=main)
          echo "pr-number=$PR_NUMBER" >> "$GITHUB_OUTPUT"
      - name: Echo result PR number
        run: |
          echo "get-pr.pr-number: ${{ steps.get-pr.outputs.pr-number }}"
          echo "create-pr.pr-number: ${{ steps.create-pr.outputs.pr-number }}"
